config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'

  get    'signup' => 'users#new'
  get 	 'login'  => 'sessions#new'
  post 	 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 	 'events' => 'events#index'

  resources :users, only: [ :new, :create, :show ]
  resources :events, only: [ :new, :create, :show ]
  resources :invites, only: [ :create , :destroy ]
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :creator, class_name: "User"
  has_many :attendees, through: :invites
  has_many :invites, through: :invites


  # Validations.
  validates :title, presence: true, length: { maximum: 50 }
  validates :location, presence: true
  validates :description, presence: true, length: { miminum: 30, maximum: 255 }
  validates :date, presence: true
  validate  :event_cant_be_in_the_past


  def event_cant_be_in_the_past
	  errors.add(:date, 'can\'t be in the past') if !date.blank? && date < Time.zone.today
  end
end

app/models/invite.rb
class Invite < ActiveRecord::Base

  belongs_to :attendee, class_name: "User", foreign_key: :attendee_id
  belongs_to :attended_event, class_name: "Event", foreign_key: :attended_event_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  # Associations.
  has_many :created_events, class_name: "Event", foreign_key: :creator_id
  has_many :attended_events, through: :invites
  has_many :invites, foreign_key: :attendee_id

  # Callbacks


  # Validations
  validates :name, presence: true, length: { minimum: 5 , maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: 	true , length: { maximum: 255 },
        format: 	{ with: VALID_EMAIL_REGEX },
        uniqueness: { case_sensitive: false }




  # Generates digest for given string.
  def User.digest(string)
	  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
												  BCrypt::Engine.cost
	  BCrypt::Password.create(string, cost: cost)
  end

  # Creates new token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers the given user.
  def remember
    self.remember_token = User.new_token
	  update_attribute(:remember_digest, User.digest(remember_token))
  end

  # True if the users remember_token matches.
  def authenticated?(token)
	  digest = self.remember_digest
	  return false if digest.nil?
	  BCrypt::Password.new(digest).is_password?(token)
  end

 # Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  def upcoming_events
	  self.attended_events.to_a.select { |event| event.date > Time.zone.now }
  end

  def past_events
	  self.attended_events.to_a.select { |event| event.date < Time.zone.now }
  end















end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      flash.now[:success] = "Created"
      render 'show'
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees.paginate(page: params[:page]).order(created_at: :desc)
  end

  def index
    @events = Event.paginate(page: params[:page]).order(created_at: :desc)
  end

  private

    def event_params
      params.require(:event).permit(:title, :description, :date, :location)
    end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :correct_user , only: [ :create ]

  def create
	  @event = Event.find(params[:invite][:attended_event_id])
    current_user.invites.create(attended_event_id: @event.id)
	  redirect_to @event
  end

  def destroy
	  @invite = Invite.find(params[:id])
	  current_user.invites.destroy(@invite)
	  redirect_to :back
  end

  private

	  def correct_user
	    !current_user?(User.find(Event.find(params[:invite][:attended_event_id]).creator_id))
	  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user
      log_in @user
      flash[:success] = "Welcome"
      redirect_to root_url
    else
      flash.now[:warning] = "Incorrect User"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Private Events"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user   		 = User.find(params[:id])
	  @events 		 = @user.created_events.paginate(page: params[:page]).order(created_at: :desc)
	  @attended_events = @user.attended_events.paginate(page: params[:page]).order(created_at: :desc)
	  @upcoming_events = @user.upcoming_events
	  @past_events     = @user.past_events
  end

  private

    def user_params
      params.require(:user).permit(:name, :email)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    remember(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
	  cookies.permanent.signed[:user_id] = user.id
	  cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
	    @current_user = User.find_by(id: user_id)
	  elsif (user_id = cookies.signed[:user_id])
	    user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
		    log_in user
		    @current_user = user
      end
    end
  end

  def current_user?(user)
    current_user == user
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_attend.html.erb
<%= form_for(current_user.invites.build(attended_event_id: @event.id)) do |f| %>
  <%= f.hidden_field :attended_event_id, :value => @event.id %>
  <%= f.submit "Attend Event", class: "form-control btn btn-info center" %>
<% end %>

app/views/events/_attend_form.html.erb
<% unless current_user?(User.find(@event.creator_id)) %>
  <div id='attend_form'>
	<% if @event.attendees.include?(current_user) %>
	  <%= render 'unattend' %>
	<% else %>
	  <%= render 'attend' %>
	<% end %>
  </div>
<% end %>

app/views/events/_event.html.erb
<div class='panel panel-info'>
  <div class='panel-heading'>
	<h4 class="white-heading"><%= link_to event.title.capitalize, event %></h4>
  </div>
  <div class='panel-body'>
	<div class='event-creator'>
	  Creator: <%= User.find(event.creator_id).name %>
  </div>
	<div class='event-description'>
	  <%= event.description %>
	</div>
	<div class='loc-time'>
	  <p class='event-date text-muted'>
		<span class='glyphicon glyphicon-road'></span> <%= event.location%>
	  </p>
	  <p class="event-date">
		<span class='glyphicon glyphicon-time'></span> <%= event.date.strftime("%A, %d %b %Y %l:%M %p")%>
	  </p>
	</div>
  </div>
</div>

app/views/events/_event_form.html.erb
<%= form_for @event do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>

  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control', rows: 7, placeholder: 'Description' %>

  <%= f.label :location %>
  <%= f.text_field :location, class: 'form-control', placeholder: 'Location' %>

  <%= f.label :date %>
  <%= f.datetime_select :date, class: 'form-control' %>
  <br />

  <%= f.submit "Create event", class: 'btn btn-success sep-fixed' %>
<% end %>

app/views/events/_unattend.html.erb
<%= form_for(current_user.invites.find_by(attended_event_id: @event.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unattend event", class: "form-control btn btn-danger center" %>
<% end %>

app/views/events/index.html.erb
<h3 class='text-info center'>All events</h3>
<div class=''>
  <%= render @events %>
</div>
<div class="center-pagination">
  <%= will_paginate @events %>
</div>

app/views/events/new.html.erb
<div class='panel panel-success'>
  <div class='panel-heading'><h4 class="white-heading">Create an event</h4></div>
  <div class='panel-body'>
	<%= render 'event_form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class='row'>
<div class='col-md-4'>
  <div class='panel panel-info'>
	<div class='panel-heading'>
	  <% if !@attendees.nil? and @attendees.count != 0 %>
		<h4 class='white-heading attendees'>Users attending(<%= @attendees.count %>)</h4>
	  <% else %>
		  <h4 class='white-heading'>Invite some users!</h4>
	  <% end %>
	</div>
	<div class='panel-body'>
	  <% if !@attendees.nil? and @attendees.count != 0 %>
		<%= render @attendees %>
	  <% else %>
	    <h4 class='text-warning events-heading'>There are no users attending to this event</h4>
	  <% end %>
	</div>
  </div>
</div>
<div class='col-md-8'>
  <div class='panel panel-info'>
	<div class='panel-heading'>
	  <h4 class="white-heading"><%= @event.title.capitalize %></h4>
	</div>
	<div class='panel-body'>
	  <div class='event-creator'>
		Creator: <%= User.find(@event.creator_id).name %>
	  </div>
	  <div class='event-description'>
		<%= @event.description %>
	  </div>
	  <div class='loc-time'>
		<p class='event-date text-muted'>
		  <span class='glyphicon glyphicon-road'></span> <%= @event.location%>
		</p>
		<p class="event-date">
		  <span class='glyphicon glyphicon-time'></span> <%= @event.date.strftime("%A, %d %b %Y %l:%M %p")%>
		</p>
	  </div>
	</div>
  </div>
  <div class="attend-form">
	<% if @event.date < Time.zone.now %>
	  <h4 class='danger'>This event has already finished!</h4>
	<% else %>
	  <%= render 'attend_form' if logged_in? %>
	<% end %>
  </div>
</div>
</div>
<% if !@attendees.nil? %>
  <div class='row'>
	<%= will_paginate @attendees %>
  </div>
<% end %>

app/views/invites/create.js.erb
$("#attend_form").html("<%= escape_javascript(render('events/unattend')) %>")

app/views/invites/destroy.js.erb
$("#attend_form").html("<%= escape_javascript(render('events/attend')) %>")

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="my-footer">
	  <small>
	    <p class='pull-left text-muted'>Private-Events</p>
    </small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div role='navigation' class='navbar navbar-default navbar-fixed-top'>
  <div class='container'>
	  <div class='navbar-header'>
	    <%= link_to "Private-Events", "#", class: 'navbar-brand' %>
	  </div>
    <div class='navbar-collapse collapse'>
	    <ul class='nav navbar-nav navbar-right'>
		    <li class="active">
		      <%= link_to "Home", root_url %>
		    </li>
		    <li><%= link_to "Events", events_url %></li>
		    <% if logged_in? %>
		    <li class="dropdown">
			    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><span class="caret"></span></a>
			    <ul class="dropdown-menu">
			      <li class="dropdown-header">User</li>
			      <li><%= link_to "Profile", current_user %></li>
			      <li><%= link_to "My events" , current_user %></li>
			      <li><%= link_to "Create event", new_event_url %></li>
			      <li class="divider"></li>
			      <li><%= link_to "Log out", logout_path, method: :delete %></li>
		  	  </ul>
		    </li>
		    <% else %>
		    <li><%= link_to "Log in", login_path %></li>
		    <% end %>
	    </ul>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container not-fixed">
  	<div class="row">
  	  <div class="col-md-8 col-md-offset-2">
  		  <% flash.each do |message_type, message| %>
  		  <div class="alert alert-<%= message_type %>"><%= message %></div>
  		  <% end %>
  		  <%= yield %>
  	  </div>
  	</div>
  </div>

  <%= render 'layouts/footer' %>


<%= javascript_include_tag 'dropdown.js' %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, 'error') %>.
    </div>
	<div class="error-messages">
	  <% object.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"><%= msg %></div>
	  <% end %>
	</div>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1 class='text-info'>Private-Events, based on EventBrite</h1>
  <p>
	  Create a new event, join an existing one or just browse and enjoy!
  </p>
  <center>
	  <% if logged_in? %>
	    <%= link_to "Create an event!", new_event_path, class: "btn btn-lg btn-info"  %>
	  <% else %>
	    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-info" %>
	  <% end %>
  </center>
</div>

app/views/users/_user.html.erb
<h4 class='text-primary'><%= link_to user.name, user%></h4>

app/views/users/new.html.erb
<div class='row'>
  <div class='col-md-8 col-md-offset-2'>
	  <div class='panel panel-info'>
	    <div class='panel-heading'>
		    <h1>User signup</h1>
	    </div>
	    <div class='panel-body'>
		    <%= form_for @user do |f| %>
		      <%= render 'shared/error_messages', object: f.object %>
		      <%= f.label :name %>
		      <%= f.text_field :name, class: 'form-control' %>

		      <%= f.label :email %>
		      <%= f.email_field :email, class: 'form-control' %>

		    <br />
		      <%= f.submit "Signup", class: 'btn btn-info' %>
		      <p class='text-muted'>Already have an account? <%= link_to 'Log in!', login_path %></p>
		    <% end %>

	    </div>
	  </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='row'>
  <div class='col-md-4'>
	  <div class="panel panel-info">
	    <div class='panel-heading'>
		    <h4 class='text-primary'><%= @user.name %></h4>
	    </div>
	    <div class='panel-body'>
		    This is my profile.
	    </div>
	  </div>
  </div>
  <div class='col-md-8'>
	  <h4 class='text-primary events-heading'>My events(<%= @user.created_events.count%>)</h4>
	  <% if @events.any? %>
	    <%= render @events %>
	  <% else %>
	    <h4 class="text-warning">This user has no events yet!</h4>
	  <% end %>
	  <%= will_paginate @events %>
  </div>
</div>
<div class='row draw-line'>
  <div class='col-md-6'>
	  <% if @upcoming_events.any? %>
	    <h4 class='text-primary events-heading'>Upcoming events(<%= @upcoming_events.count %>)</h4>
	    <%= render @upcoming_events %>
	  <% else %>
	    <h4 class='text-warning events-heading'>You have no upcoming events</h4>
	  <% end %>
  </div>
  <div class='col-md-6'>
	  <% if @past_events.any? %>
	    <h4 class='text-primary events-heading'>Past events(<%= @past_events.count %>)</h4>
	    <%= render @past_events %>
	  <% else %>
	    <h4 class='text-warning events-heading'>You have no past events</h4>
  	<% end %>
  </div>
</div>